### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by FinnFurwolf** [Treaxy/AnomalyHub#1]
Would be nice to have an option to give the Cassie announcements a delay, when they should be played. I also have Serpents Hand on my server and as this counts as a Chaos spawn, both messages trigger at the same time.

FriendlyFire resets on round start, so the server is listed as FF on, as long, as you are in the lobby or if the server is empty. This could be fixed, if FF resets on round restart.

**Comment by Treaxy** [comment]
Thanks for suggestions.

**Comment by FinnFurwolf** [comment]
FF is now permanently on. It doesn't get reset.

**Comment by Treaxy** [comment]
Fixed
